stages:
  - install
  - test
  - build-sonar
  - build
  - deploy

default:
  image: node:20

variables:
  NODE_ENV: production
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

# Install backend dependencies
install_backend:
  stage: install
  script:
    - cd application/backend
    - npm install --legacy-peer-deps
  artifacts:
    paths:
      - application/backend/node_modules/

# Install frontend dependencies
install_frontend:
  stage: install
  script:
    - cd application/frontend
    - npm install --legacy-peer-deps
  artifacts:
    paths:
      - application/frontend/node_modules/

# Frontend tests
test_frontend:
  stage: test
  script:
    - cd application/frontend
    - npm install --legacy-peer-deps --include=dev
    - npm test
  artifacts:
    when: always
    paths:
      - application/frontend/test-results/
    reports:
      junit: application/frontend/test-results/junit.xml
  allow_failure: false

# Build frontend
build_frontend:
  stage: build
  script:
    - cd application/frontend
    - npm install --legacy-peer-deps --include=dev
    - npm run build
  artifacts:
    paths:
      - application/frontend/dist

# Build backend
build_backend:
  stage: build
  script:
    - cd application/backend
    - npm install --legacy-peer-deps --include=dev
  artifacts:
    paths:
      - application/backend/node_modules/


sonarqube-check:
  stage: build-sonar
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'dev'

# Deploy frontend
deploy_frontend:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
      allow_failure: false
  variables:
    RAILWAY_TOKEN: $RAILWAY_TOKEN
    FRONTEND_SVC_ID: $RAILWAY_FRONTEND_SVC_ID
    PROJECT_ID: $RAILWAY_PROJECT_ID
  script:
    - cd application/frontend
    - railway up --service=$FRONTEND_SVC_ID

# Deploy backend
deploy_backend:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
      allow_failure: false
  variables:
    RAILWAY_TOKEN: $RAILWAY_TOKEN
    BACKEND_SVC_ID: $RAILWAY_BACKEND_SVC_ID
    PROJECT_ID: $RAILWAY_PROJECT_ID
  script:
    - ls
    - cd application/backend
    - railway up --service=$BACKEND_SVC_ID