// rooms
export const ROOMS_LOADING = 'ROOMS_LOADING';
export const ROOMS_OK = 'ROOMS_OK';
export const ROOMS_ERROR = 'ROOMS_ERROR';

export const CREATE_ROOM_LOADING = 'CREATE_ROOM_LOADING';
export const CREATE_ROOM_OK = 'CREATE_ROOM_OK';
export const CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR';

export const ROOM_LOADING = 'ROOM_LOADING';
export const ROOM_OK = 'ROOM_OK';
export const ROOM_ERROR = 'ROOMS_ERROR';

export const PRICE_HISTORY_LOADING = 'PRICE_HISTORY_LOADING';
export const PRICE_HISTORY_OK = 'PRICE_HISTORY_OK';
export const PRICE_HISTORY_ERROR = 'PRICE_HISTORY_ERROR';

export const EQUIPMENT_LOADING = 'EQUIPMENT_LOADING';
export const EQUIPMENT_OK = 'EQUIPMENT_OK';
export const EQUIPMENT_ERROR = 'EQUIPMENT_ERROR';

export const OCCUPANCY_LOADING = 'OCCUPANCY_LOADING';
export const OCCUPANCY_OK = 'OCCUPANCY_OK';
export const OCCUPANCY_ERROR = 'OCCUPANCY_ERROR';


// reservations
export const RESERVATIONS_LOADING = 'RESERVATIONS_LOADING';
export const RESERVATIONS_OK = 'RESERVATIONS_OK';
export const RESERVATIONS_ERROR = 'RESERVATIONS_ERROR';

export const CREATE_RESERVATION_LOADING = 'RESERVATION_CREATE_LOADING';
export const CREATE_RESERVATION_OK = 'RESERVATION_CREATE_OK';
export const CREATE_RESERVATION_ERROR = 'RESERVATION_CREATE_ERROR';

export const RESERVATION_LOADING = 'RESERVATION_LOADING';
export const RESERVATION_OK = 'RESERVATION_OK';
export const RESERVATION_ERROR = 'RESERVATION_ERROR';


// guests
export const GUESTS_LOADING = 'GUESTS_LOADING';
export const GUESTS_OK = 'GUESTS_OK';
export const GUESTS_ERROR = 'GUESTS_ERROR';

export const GUEST_LOADING = 'GUEST_LOADING';
export const GUEST_OK = 'GUEST_OK';
export const GUEST_ERROR = 'GUEST_ERROR';