// rooms
export const ROOMS_LIST_LOADING = 'ROOMS_LIST_LOADING';
export const ROOMS_LIST_OK = 'ROOMS_LIST_OK';
export const ROOMS_LIST_ERROR = 'ROOMS_LIST_ERROR';

export const CREATE_ROOM_LOADING = 'CREATE_ROOM_LOADING';
export const CREATE_ROOM_OK = 'CREATE_ROOM_OK';
export const CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR';

export const ROOM_LOADING = 'ROOM_LOADING';
export const ROOM_OK = 'ROOM_OK';
export const ROOM_ERROR = 'ROOMS_ERROR';

export const PRICE_HISTORY_LOADING = 'PRICE_HISTORY_LOADING';
export const PRICE_HISTORY_OK = 'PRICE_HISTORY_OK';
export const PRICE_HISTORY_ERROR = 'PRICE_HISTORY_ERROR';

export const EQUIPMENT_LOADING = 'EQUIPMENT_LOADING';
export const EQUIPMENT_OK = 'EQUIPMENT_OK';
export const EQUIPMENT_ERROR = 'EQUIPMENT_ERROR';